title: My InfoSec Blog
description: My InfoSec Blog
author: Capt. Meelo
github: https://github.com/capt-meelo
about: An infosec noob who's constantly seeking for knowledge.
google_analytics: UA-121401658-1
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/CaptMeelo"
    - icon: fa-github
      link: "https://github.com/capt-meelo"

share:
  twitter_username: CaptMeelo

urls:
    - text: Pen Test
      url: /category/pentest
    - text: Exploit Dev
      url: /category/exploitdev
    - text: Bug Bounty
      url: /category/bugbouty
    - text: Disclosures
      url: /category/disclosures  
    - text: About Me
      url: /about/
      
url: "https://capt-meelo.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
