title: Capt. Meelo
description: My Personal Blog
author: Capt. Meelo
github: https://github.com/capt-meelo
about: An infosec noob who's constantly seeking for knowledge.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/CaptMeelo"
    - icon: fa-github
      link: "https://github.com/capt-meelo"

share:
  twitter_username: CaptMeelo

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://capt-meelo.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
